### ISSUE TITLE
[Bug]: Completions in (at least) ZSH are a bit broken outside of Git repos

### ISSUE THREAD

**Issue by jiriks74** [mateusauler/git-worktree-switcher#1]
When you press tab while using `wt` outside of a git repo the error from the completion breaks the shell prompt a bit. See recording below.

<details>
<summary>Recording</summary>

> [!Note]
> Don't mind the spam, I just pressed tab multiple times

![git-worktree-switcher completion-issues](https://github.com/user-attachments/assets/4c55fbd9-93e3-4e7e-b5e2-5f94d1a0f744)

</details>

**Comment by mateusauler** [comment]
Sorry for the delay! I somehow completely missed the issue and the bug itself.
Should be fixed now. I'll ship a new release with it soon.
